// frontend/react/src/components/TodoList.js
import { useState, useEffect } from "react"
import { useNavigate } from "react-router-dom";
import AddTodo from "./AddTodo"
import Todos from "./Todos"
import LogOut from "./LogOut"

const TodoList = ({ loggedIn, token, setLoggedIn }) => {
    const [todos, setTodos] = useState([])
    let navigate = useNavigate()
    useEffect(() => {
        fetchTodos((res) => {
            if (res.detail && res.detail === "Forbidden") {
                navigate("/")
                return
            }
            setTodos(res)
        })
    }, [])

    const fetchTodos = async (callback) => {
        const response = await fetch('http://localhost:8001/?token=' + token)
        const data = await response.json()
        return callback(data)
    }


    const addTodo = async (todo) => {
        const response = await fetch('http://localhost:8001', {
            method: "POST",
            headers: {
                'Content-type': 'application/json'
            },
            body: JSON.stringify(todo)
        })
        const data = await response.json()

        setTodos([...todos, data])

    }

    const removeTodo = async (id) => {
        await fetch(`http://localhost:8001/${id}`, {
            method: "DELETE",
        })
        setTodos(todos.filter((todo) => todo.id !== id))
    }
    return (
        <>
            {loggedIn
                && <div className="container">
                    <AddTodo onAdd={addTodo} />
                    <LogOut setLoggedIn={setLoggedIn} navigate={navigate} />
                    <Todos onRemove={removeTodo} todos={todos} />
                </div>}
        </>
    )
}

export default TodoList

// frontend/vue/src/components/ToDoList.vue
<template>
    <div class="to-do-list">
        <UserControlPanel @add-to-do="addToDo" />
        <ToDos @delete-todo="deleteToDo" :todos="todos" />
    </div>
</template>

<script>
import UserControlPanel from './UserControlPanel.vue'
import ToDos from './ToDos.vue'
export default {
    name: 'ToDoList',
    components: {
        UserControlPanel,
        ToDos
    },
    methods: {
        async deleteToDo(todo_id) {
            try {
                const res = await fetch(`http://127.0.0.1:8001/${todo_id}`, {
                    method: 'DELETE',
                })
                if (!res.ok) {
                    throw new Error(`HTTP error: ${res.status}`)
                }
                this.todos = this.todos.filter((todo) => todo.id !== todo_id)

            } catch (error) {
                console.dir(error)
            }

        },

        async addToDo(todo) {
            try {
                const res = await fetch('http://127.0.0.1:8001/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify(todo),
                })
                if (!res.ok) {
                    throw new Error(`HTTP error: ${res.status}`)
                }
                const data = await res.json()

                this.todos = [...this.todos, data]
            } catch (error) {
                console.dir(error)
            }

        },

        async fetchTodos() {
            const res = await fetch('http://127.0.0.1:8001/')

            const data = await res.json()

            return data
        }

    },
    data() {
        return {
            todos: []
        }
    },
    async created() {
        this.todos = await this.fetchTodos()
    }
}
</script>

<style>
body {
    background-color: #e7e7e7;
    font-family: sans-serif;
}

.to-do-list {
    height: 400px;
    aspect-ratio: 0.8;
    background-color: white;
    margin: 0 auto;
    margin-top: 5em;
    position: relative;
    padding: 15px;
    box-sizing: border-box;
}

.to-do-list>div {
    margin: 15px 0;
}
</style>
